#!/bin/bash

unset GREP_OPTIONS
urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }

url=$(echo "$1" | sed "s/\?.*//g")
if [[ $url == *"/detail/"* ]] || [[ $url == *"/status/"* ]] || [ ${#1} -eq 16 ]
then
	tid=$(echo $url | sed "s/.*weibo\.cn\/\(detail\|status\)\///g")
	urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }
	uid=$(curl "https://m.weibo.cn/detail/$tid" | egrep -o "\"profile_url\": \"https://[^?\"]+" | egrep -o "[0-9]+$")
	echo fech phone: uid: $uid, tid: $tid
	mkdir -p site/$uid/$tid

	for img in $(curl "https://m.weibo.cn/detail/$tid" | egrep -o "\"url\": \"https://wx[1-4]\.sinaimg\.cn\/large\/[^\"]+\"" | sed "s/\"url\": \"\([^\"]\+\)\"/\\1/g")
	do
		echo $uid/$tid: $img
		wget -c -b --tries=inf -P site/$uid/$tid -o site/$uid/$tid-$(echo $img | sed "s/.*\///g;s/\.[^\.]*$//g").log "$img"
	done
else
	target=$(echo $url | sed "s/.*weibo\.com\///g")
	target=${target/-/\/}
	echo fech web page: $target
	mkdir -p site/$target

	imgs=$(curl "https://www.weibo.com/$target" --compressed -H "DNT: 1" -H "TE: Trailers" -H "Connection: keep-alive" -H "Upgrade-Insecure-Requests: 1" \
		-H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Accept-Language: zh-CN,en-US;q=0.8,en;q=0.5,zh-TW;q=0.3" \
		-H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0" \
		-H "Cookie: $(cat cookie-sina.txt)" | egrep -o "clear_picSrc=[^&]+" | egrep -o "%2F%2Fw.[^,]+")
	for img in $imgs
	do
		echo https:$(urldecode "$img") | sed "s/mw690/large/g" >> site/$target.list
	done
	cat site/$target.list
	wget -c -b --tries=inf -P site/$target -i site/$target.list -o site/$target.log
fi
